add Search Shelfs
Misha2048/CatharsisX-back pull request #11
Opened 2023-12-22 15:43 UTC by Spinkll

2023-12-22 16:35 UTC, Misha2048 requested changes
Smells like shit, like

2023-12-22 16:35 UTC, Misha2048 commented on src/modules/shelfs/shelfs.controller.ts
> +  ValidationPipe,
Слишком много импортов не по делу

2023-12-22 16:35 UTC, Misha2048 commented on src/modules/shelfs/shelfs.service.ts
> +      },
Bad practice. Если мы решим расширить полку, то придется переделывать это все. Лучше это реализовать на уровень абстракции ниже, типа что не андефайнд, то рассматриваем как фильтр

2023-12-23 11:12 UTC, Misha2048 approved these changes

2023-12-23 13:25 UTC, Misha2048 approved these changes

2023-12-23 13:30 UTC, Daniel04203 approved these changes

2023-12-23 13:48 UTC, merged