add chat and message schema
Misha2048/CatharsisX-back pull request #116
Opened 2024-03-08 12:49 UTC by Spinkll

2024-03-09 08:25 UTC, Misha2048 requested changes

2024-03-09 08:25 UTC, Misha2048 commented on prisma/schema.prisma
> +  chatId         String?
А зачем это поле юзеру? Он может быть во многих чатах, а не только в одном

2024-03-09 08:25 UTC, Misha2048 commented on prisma/schema.prisma
> +  message          Message[]
Нам нужно в чате это поле?

2024-03-10 10:28 UTC, Misha2048 approved these changes

2024-03-10 10:37 UTC, Daniel04203 approved these changes

2024-03-10 10:38 UTC, merged