Feature/message sent ws event
Misha2048/CatharsisX-back pull request #117
Opened 2024-03-11 10:43 UTC by Spinkll

2024-03-12 08:36 UTC, Misha2048 requested changes
smells like... well, dunno

2024-03-13 08:43 UTC, Misha2048 requested changes
Well, I have not smell it so much earlier like now, few!

2024-03-13 08:43 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +
Сначала найти чат по user_id, если чата нет, то создать новый чат с user_id

2024-03-13 08:43 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +        userId: sendMessageRequestDto.target,
тут не таргет, а айди юзера из сокет сессии

2024-03-13 08:43 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +      .filter((user) => user.id !== socket.id)
socket.id - это не user_id, это sid, нужно, чтоб проверка была именно на id юзера

2024-03-13 08:43 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +      if (user) {
Вместо того, чтобы делать вложенные блоки, лучше проверить отсутствие юзера (!user) и при выполненнии условия выбить ошибку

2024-03-13 12:01 UTC, Misha2048 commented on src/modules/socket/socket.gateway.ts
> +    socket['user'] = payload;
Может, вместо содержимого токена, лучше найти юзера по айди и записать сам объект юзера?

2024-03-13 12:07 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +    userId: string,
В сокете же есть объект юзера, зачем отдельно айди передавать?

2024-03-13 12:33 UTC, Spinkll commented on src/modules/socket/socket.gateway.ts
> +    socket['user'] = payload;
`const payload = await this.jwtService.verifyAsync(token);
      const user = await this.usersService.findById(payload.id);

      socket['user'] = user;
      this.socketService.handleConnection(socket);`

2024-03-13 12:33 UTC, Spinkll commented on src/modules/socket/socket.gateway.ts
> +    socket['user'] = payload;
типа вот так вот ?

2024-03-13 12:35 UTC, Spinkll commented on src/modules/socket/socket.gateway.ts
> +    socket['user'] = payload;
можно сделать socket.user = user но тогда нужно добавить тип юзера в socket

2024-03-13 13:56 UTC, Misha2048 requested changes

2024-03-13 13:56 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +    let chat = await client.chat.findFirst({
На этом моменте, мы предполагаем, target - это айди чата, а не айди одного из юзеров, нужно искать по айди чата

2024-03-13 13:56 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +      chat = await client.chat.create({
Мы не создаем сразу чат, а проверяем, есть ли в чате юзер с таким айди

2024-03-13 15:14 UTC, Spinkll commented on src/modules/socket/socket.service.ts
> +      chat = await client.chat.create({
переделал

2024-03-13 15:45 UTC, Misha2048 requested changes

2024-03-13 15:45 UTC, Misha2048 commented on src/modules/socket/socket.gateway.ts
> +    this.socketService.handleSendMessage(socket, sendMessageRequestDto);
Где async?

2024-03-13 15:45 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +          { users: { some: { id: sendMessageRequestDto.target } } },
Мы проверяем ТОЛЬКО айди чата

2024-03-13 21:26 UTC, Misha2048 approved these changes

2024-03-13 21:34 UTC, PavloDolia approved these changes

2024-03-13 21:35 UTC, merged