add response_history
Misha2048/CatharsisX-back pull request #118
Opened 2024-03-13 23:40 UTC by Spinkll

2024-03-14 08:27 UTC, Misha2048 requested changes
A little bit of shit, not many, really

2024-03-14 08:27 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +      acc[date] = obj.content;
Not an array, it is shit. 

Нужно на фронт передавать объект сообщения, а не только контент

2024-03-14 08:27 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +        where: { id: message.id },
{ id: message.id, read: false }

2024-03-15 08:41 UTC, Misha2048 requested changes
Mostly not a shit

2024-03-15 08:41 UTC, Misha2048 commented on src/modules/socket/socket.service.ts
> +      const unreadMessages = history.filter(
Well, could you please dew it with sql?

2024-03-15 08:43 UTC, Misha2048 approved these changes

2024-03-15 08:43 UTC, PavloDolia approved these changes

2024-03-15 08:44 UTC, merged