add Stillage indexation
Misha2048/CatharsisX-back pull request #20
Opened 2024-01-03 12:21 UTC by Spinkll

2024-01-04 18:33 UTC, Misha2048 requested changes
По бд все ок, но логику, пожалуйста, убери, она пока не нужна

2024-01-04 18:33 UTC, Misha2048 requested changes
По бд все ок, но логику, пожалуйста, убери, она пока не нужна

2024-01-05 10:06 UTC, holotsvan approved these changes

2024-01-05 12:03 UTC, Misha2048 approved these changes

2024-01-05 12:03 UTC, merged