Feature/scrum 56 added an endpoint for the shelf model update fields by Makarov Danylo
Misha2048/CatharsisX-back pull request #22
Opened 2024-01-05 13:25 UTC by Daniel04203

2024-01-06 13:08 UTC, Misha2048 requested changes

2024-01-06 13:08 UTC, Misha2048 commented on src/modules/shelfs/shelfs.controller.ts
> +      updateShelfRequest.stillage !== undefined &&
if (stillage) {}
Этого достаточно

2024-01-06 13:08 UTC, Misha2048 commented on src/modules/shelfs/shelfs.controller.ts
> +      if (value !== undefined || value !== null) {
Лучше проверять только на undefined

2024-01-06 13:08 UTC, Misha2048 commented on src/modules/shelfs/shelfs.controller.ts
> +      console.log(shelf.error_message);
Лог убрать

2024-01-06 13:08 UTC, Misha2048 commented on src/modules/shelfs/shelfs.service.ts
> +      const errorCodes = {
Этот объект лучше объявить локальном скоупе

2024-01-07 14:06 UTC, Misha2048 approved these changes

2024-01-07 14:08 UTC, Spinkll approved these changes

2024-01-07 14:09 UTC, merged