add upload file
Misha2048/CatharsisX-back pull request #23
Opened 2024-01-06 14:20 UTC by Spinkll

2024-01-06 14:35 UTC, Misha2048 requested changes
По логике ок, но есть пара моментов

2024-01-06 14:35 UTC, Misha2048 commented on .env.sample
> +x-api-key="SECRET_KEY"
Энвы пишутся капсом и снейккейсом

+ лучше его обозвать AI_API_KEY, или что-то вроде того

2024-01-06 14:35 UTC, Misha2048 commented on src/dto/file.ts
> +  stillage_id: string;
Не обязательно в реквесторе стиллаж передавать, потому что он есть в полке

2024-01-06 14:35 UTC, Misha2048 commented on src/modules/files/files.service.ts
> +      if (process.env.VALIDATE_FILES === 'true') {
Можно заменить на

if (!env) {
    return true;
}

Вместо большого условия на весь метод

2024-01-06 14:35 UTC, Misha2048 commented on src/modules/files/files.service.ts
> +                  HttpStatus.INTERNAL_SERVER_ERROR,
Может лучше кидать какую-то из 400+?

2024-01-06 14:35 UTC, Misha2048 commented on src/modules/files/files.service.ts
> +      } else {
Else необязателен

throw new error - останавливает выполнение дальнейшего кода

2024-01-07 15:51 UTC, Misha2048 approved these changes

2024-01-07 16:18 UTC, Misha2048 approved these changes

2024-01-07 16:18 UTC, Misha2048 approved these changes

2024-01-07 16:20 UTC, PavloDolia approved these changes

2024-01-07 16:37 UTC, merged