Added toggle property status
Misha2048/CatharsisX-back pull request #32
Opened 2024-01-11 15:05 UTC by Daniel04203

2024-01-11 19:23 UTC, Misha2048 requested changes

2024-01-11 19:23 UTC, Misha2048 commented on package.json
> +    "prisma": "^5.8.0",
Зачем менять версию призмы?

2024-01-11 19:23 UTC, Misha2048 commented on src/modules/stillages/stillages.controller.ts
> +  })
Можем ли мы это сделать в рамках эндпоинта апдейта стеллажа?

2024-01-11 19:26 UTC, Daniel04203 commented on package.json
> +    "prisma": "^5.8.0",
Насправді, мені просто запропонували оновитись.

2024-01-11 19:28 UTC, Daniel04203 commented on src/modules/stillages/stillages.controller.ts
> +  })
Ні, не можемо, бо там відбувається оновлення назви, а тут кожного разу після звернення оновлюється статус private / public.

2024-01-11 19:30 UTC, Misha2048 commented on package.json
> +    "prisma": "^5.8.0",
Верни, пожалуйста, прошлую версию

2024-01-11 19:30 UTC, Misha2048 commented on src/modules/stillages/stillages.controller.ts
> +  })
Так патч стеллажа на то и нацелен, чтоб частично обновить объект, если его названия нет в реквесте, то и обновлять его не надо

2024-01-11 19:30 UTC, Daniel04203 commented on package.json
> +    "prisma": "^5.8.0",
Добре, спробую завтра це зробити.

2024-01-11 19:31 UTC, Misha2048 commented on src/modules/stillages/stillages.controller.ts
> +  })
Смысл кучу эндпоинтов плодить?

2024-01-11 19:31 UTC, Daniel04203 commented on src/modules/stillages/stillages.controller.ts
> +  })
А, тоді можна спробувати.

2024-01-12 18:26 UTC, Misha2048 requested changes

2024-01-12 18:26 UTC, Misha2048 commented on src/dto/stillages.ts
> +  property_status?: boolean;
Невалидная сигнатура, если это булеан, то лучше назвать private

2024-01-12 18:26 UTC, Misha2048 commented on src/modules/stillages/stillages.controller.ts
> +        stillage.property_status === 'private' ? 'public' : 'private';
Лишняя логика, этот статус уже является булеаном

2024-01-12 18:26 UTC, Misha2048 commented on src/modules/stillages/stillages.controller.ts
> +        stillage.property_status === 'private' ? 'public' : 'private';
Лучше этот статус добавить в реквест

2024-01-12 18:48 UTC, Daniel04203 commented on src/dto/stillages.ts
> +  property_status?: boolean;
Не дуже зрозумів, іще раз можна більш детально¿¿??

2024-01-12 18:51 UTC, Daniel04203 commented on src/dto/stillages.ts
> +  property_status?: boolean;
Міш, за ідеєю, із forntend - у ми отримуємо true або false, або взагалі нічого не отримуємо. Якщо ми отримуємо true, то далі змінюємо значення протилежне ("private" або "public"(string)) у базі, чи це занадто¿¿??

2024-01-15 08:26 UTC, Misha2048 requested changes
Some shit

2024-01-15 08:26 UTC, Misha2048 commented on prisma/schema.prisma
> +  property_status String    @default("private")
Пусть это полу называется private: bool

2024-01-15 20:18 UTC, Misha2048 requested changes

2024-01-15 20:18 UTC, Misha2048 commented on prisma/schema.prisma
> +  private_property_status   Boolean    @default(true)
Неоправданно длинная сигнатура

2024-01-15 20:18 UTC, Misha2048 commented on src/modules/stillages/stillages.controller.ts
> +    if (updateStillageRequest.private_property_status != undefined) {
Зачем отдельно это условие?

2024-01-16 08:30 UTC, Misha2048 commented on prisma/schema.prisma
> +  private_property_status   Boolean    @default(true)
private

2024-01-16 11:34 UTC, Misha2048 approved these changes

2024-01-16 11:47 UTC, Spinkll approved these changes

2024-01-16 11:47 UTC, merged