Changed endpoint for getting an object both with an id of university …
Misha2048/CatharsisX-back pull request #34
Opened 2024-01-12 13:44 UTC by Daniel04203

2024-01-12 18:22 UTC, Misha2048 requested changes

2024-01-12 18:22 UTC, Misha2048 commented on src/modules/universities/universities.controller.ts
> +    type: GetUniversitiesResponseDto,
Контроллер не вернет этот тип, сервис возвращает University[], позже же в дто это не форматируется

2024-01-13 15:57 UTC, Daniel04203 commented on src/modules/universities/universities.controller.ts
> +    type: GetUniversitiesResponseDto,
Добре, тоді залишити type: Prisma.ModelName.University, isArray: true;???
Чи достатньо type: Object, isArray: true???

2024-01-15 20:16 UTC, Misha2048 approved these changes

2024-01-16 07:55 UTC, Spinkll approved these changes

2024-01-16 08:04 UTC, merged