change logic of stillages.service filter to be consistent with shelf.…
Misha2048/CatharsisX-back pull request #38
Opened 2024-01-19 10:27 UTC by holotsvan

…service filter

2024-01-22 18:30 UTC, PavloDolia requested changes

2024-01-22 18:30 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +  const formattedDate = timestamp.toISOString().slice(0, 10); // Extract YYYY-MM-DD
method toISOString() can [cause some bugs](https://stackoverflow.com/questions/43670062/get-iso-string-from-a-date-without-time-zone). Method setHours(0, 0, 0, 0) should be used here

2024-01-23 09:17 UTC, PavloDolia approved these changes
I guess it should work fine

2024-01-23 09:40 UTC, Spinkll approved these changes

2024-01-23 09:40 UTC, merged