add response
Misha2048/CatharsisX-back pull request #39
Opened 2024-01-19 23:56 UTC by Spinkll

2024-01-20 08:48 UTC, PavloDolia requested changes

2024-01-20 08:48 UTC, PavloDolia commented on src/dto/catalog.ts
треба видилити цей файл, там response інший буде, я його напишу

2024-01-20 08:48 UTC, PavloDolia commented on src/modules/catalog/catalog.controller.ts
треба видилити цей файл, там response інший буде, я його напишу

2024-01-20 16:15 UTC, PavloDolia approved these changes

2024-01-22 18:58 UTC, PavloDolia approved these changes

2024-01-23 08:26 UTC, Misha2048 approved these changes
Do not smells like shit, so I guess it is alright

2024-01-23 08:39 UTC, merged