fix/scrum-105 add liked prop
Misha2048/CatharsisX-back pull request #41
Opened 2024-01-20 19:47 UTC by PavloDolia

2024-01-21 17:37 UTC, Misha2048 requested changes

2024-01-21 17:37 UTC, Misha2048 commented on src/modules/stillages/stillages.service.ts
> +        where: { id: userId },
Необязательно, что лайкнутые стеллажи принадлежат юзеру

2024-01-21 17:37 UTC, Misha2048 commented on src/modules/stillages/stillages.service.ts
> +    })) as unknown as FindStillagesResponseDto[];
Что за конструкция

2024-01-21 17:47 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +        where: { id: userId },
Тут шукаємо масив с ID стелажей, які саме цей юзер лайкнув, щоб потім можна було відрізнити які стелажі пролайкані, а які ні

2024-01-21 18:55 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +    })) as unknown as FindStillagesResponseDto[];
змінив це на мапінг з використанням FindStillagesResponseDto

2024-01-21 19:00 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +        where: { id: userId },
цей масив зберігається у юзера

2024-01-21 19:01 UTC, Misha2048 requested changes

2024-01-21 19:01 UTC, Misha2048 commented on src/modules/stillages/stillages.service.ts
> +        user: { id: userId },
Необязательно, что стеллаж принадлежит юзеру...

2024-01-21 20:19 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +        user: { id: userId },
згоден, прибрав userId

2024-01-22 17:25 UTC, Misha2048 approved these changes

2024-01-22 17:33 UTC, holotsvan approved these changes

2024-01-22 17:33 UTC, Daniel04203 approved these changes

2024-01-22 17:34 UTC, merged