delete queryRaw in catalog and GetLikedStillages
Misha2048/CatharsisX-back pull request #46
Opened 2024-01-21 19:18 UTC by Spinkll

2024-01-21 19:20 UTC, Misha2048 commented on src/modules/catalog/catalog.service.ts
> +const prisma = new PrismaClient();
Зачем новый клиент?

2024-01-22 17:27 UTC, PavloDolia requested changes

2024-01-22 17:27 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +    const likedStillages = await client.stillage.findMany({
these stillages should be sorted by name

2024-01-22 18:22 UTC, PavloDolia approved these changes

2024-01-22 19:12 UTC, Misha2048 approved these changes

2024-01-22 19:13 UTC, merged

2024-01-22 19:15 UTC, PavloDolia requested changes

2024-01-22 19:15 UTC, PavloDolia commented on src/modules/catalog/catalog.service.ts
> +        userId: userId,
каталог повинен повертати абсолютно всі стелажі