add a color to stillages
Misha2048/CatharsisX-back pull request #68
Opened 2024-02-09 13:55 UTC by Spinkll

2024-02-09 18:01 UTC, PavloDolia commented
Треба змінити метод `getLikedStillages` в `stillages.service.ts`, тому що там не використовується жоден dto і проперті `color` не буде у відповіді.

2024-02-09 18:02 UTC, PavloDolia requested changes
Треба змінити метод getLikedStillages в stillages.service.ts, тому що там не використовується жоден dto і проперті color не буде у відповіді.

2024-02-09 18:03 UTC, Spinkll commented
![image](https://github.com/Misha2048/CatharsisX-back/assets/95828180/5b8a2e9a-6758-4ccf-a98b-54742d6bd2ef)

та начебто є

2024-02-09 18:05 UTC, Spinkll commented
побачив, в респонсі не має

2024-02-09 18:05 UTC, PavloDolia commented
окей, я тупанув, все як завжди чудово)

2024-02-09 18:05 UTC, PavloDolia approved these changes

2024-02-09 18:06 UTC, Spinkll commented
ще перероблю , бо в свагері не має 
![image](https://github.com/Misha2048/CatharsisX-back/assets/95828180/12bf2adc-b6a6-4e86-af2f-990b5de543e8)

2024-02-09 18:18 UTC, Spinkll commented
перевірив про всякий випадок ще раз , начебто все є

2024-02-10 12:32 UTC, holotsvan approved these changes

2024-02-10 12:33 UTC, merged