add create answer
Misha2048/CatharsisX-back pull request #71
Opened 2024-02-10 11:06 UTC by Spinkll

2024-02-10 12:59 UTC, Misha2048 requested changes

2024-02-10 12:59 UTC, Misha2048 commented on src/dto/answer.ts
> +export class HTTPError {
почему ошибка здесь лежит?

2024-02-10 13:00 UTC, Spinkll commented on src/dto/answer.ts
> +export class HTTPError {
Подскажи куда её покласть , типа в common ?

2024-02-10 20:55 UTC, Misha2048 commented on src/dto/answer.ts
> +export class HTTPError {
Можно туда

2024-02-10 22:28 UTC, Spinkll commented on src/dto/answer.ts
> +export class HTTPError {
сделал

2024-02-11 11:11 UTC, holotsvan approved these changes

2024-02-11 12:35 UTC, PavloDolia approved these changes

2024-02-11 20:45 UTC, Misha2048 approved these changes

2024-02-11 20:56 UTC, merged