feature/scrum-184 create the get files endpoint
Misha2048/CatharsisX-back pull request #72
Opened 2024-02-10 16:37 UTC by PavloDolia

2024-02-10 16:52 UTC, holotsvan approved these changes

2024-02-10 17:47 UTC, Misha2048 requested changes

2024-02-10 17:47 UTC, Misha2048 commented on src/dto/file.ts
> +  stillage: string;
Зачем стеллаж в реквесте?

2024-02-10 17:53 UTC, PavloDolia commented on src/dto/file.ts
> +  stillage: string;
я шукаю стелаж за його id щоб потім перевірити що він приватний або ні. Зробити пошук стелажу за shelf id?

2024-02-11 12:58 UTC, PavloDolia commented on src/dto/file.ts
> +  stillage: string;
прибрав айді стелажу із запиту

2024-02-11 13:04 UTC, Misha2048 approved these changes

2024-02-11 13:12 UTC, merged