Bug/user couldn't get other users stillages
Misha2048/CatharsisX-back pull request #78
Opened 2024-02-12 11:41 UTC by Daniel04203

2024-02-12 11:52 UTC, Misha2048 requested changes
Где же логика про приватные не юзерские стеллажи?

2024-02-12 11:55 UTC, Daniel04203 commented
> Где же логика про приватные не юзерские стеллажи?

В сенсі, можна більш детально???

2024-02-12 11:55 UTC, Daniel04203 commented
> Где же логика про приватные не юзерские стеллажи?

    if (!stillage || (stillage.private && stillage.userId != req.user['id'])) {
      throw new NotFoundException('Stillage not found');
    }

2024-02-12 11:58 UTC, Daniel04203 commented
> Где же логика про приватные не юзерские стеллажи?

І ще раз, це назва гілки, ми виправляємо роботу видачі полиць стелажів.

2024-02-12 21:32 UTC, holotsvan approved these changes

2024-02-12 21:33 UTC, PavloDolia approved these changes

2024-02-13 08:00 UTC, Misha2048 approved these changes

2024-02-13 08:01 UTC, merged