Feature/scrum 47  forgot password
Misha2048/CatharsisX-back pull request #8
Opened 2023-12-11 13:24 UTC by Spinkll

2023-12-11 13:47 UTC, Misha2048 requested changes

2023-12-11 13:47 UTC, Misha2048 commented on src/modules/auth/auth.controller.ts
> +  @Post('new-password/:id')
:id не лишний?

2023-12-11 13:47 UTC, Misha2048 commented on src/modules/auth/auth.service.ts
> -        });
Можно заменить ForgoPasswordRequest во всех местах на что-то более понятное и логичное?

2023-12-12 09:32 UTC, Misha2048 approved these changes

2023-12-12 13:41 UTC, N0UNe1m reviewed
Новый код читаемый и понятен. С автором согласен

2023-12-12 13:42 UTC, N0UNe1m approved these changes
Новый код читаемый и понятен. С автором согласен.

2023-12-12 13:47 UTC, Misha2048 approved these changes

2023-12-12 14:03 UTC, merged