Feature/download file
Misha2048/CatharsisX-back pull request #95
Opened 2024-02-18 15:10 UTC by Spinkll

2024-02-18 15:14 UTC, Misha2048 requested changes

2024-02-18 15:14 UTC, Misha2048 commented on src/modules/common/common.service.ts
> +    if (extension === '.txt') {
Лучше воспользоваться табличным методом

2024-02-18 15:14 UTC, Misha2048 commented on src/modules/files/files.service.ts
> +      if (error instanceof NotFoundException) {
Вот это вот, пожалуйста в мидлвар

2024-02-18 15:18 UTC, PavloDolia approved these changes

2024-02-18 15:18 UTC, PavloDolia commented on src/modules/common/common.service.ts
цю всю конструкцію можна змінити з викорисатнням об'єкту:
```
async getContentType(filename: string) {
     const extension = filename
       .substring(filename.lastIndexOf('.'))
       .toLowerCase();
const filesExtensions = {
  '.txt': 'text/plain',
  '.rtf': 'application/rtf',
  '.pdf': 'application/pdf',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}
    return filesExtensions[extension];
   }
```

2024-02-18 15:24 UTC, Spinkll commented on src/modules/common/common.service.ts
уже понял ,спасибо

2024-02-18 15:37 UTC, Spinkll commented on src/modules/files/files.service.ts
> +      if (error instanceof NotFoundException) {
ещё бы знать как это сделать(

2024-02-19 08:12 UTC, Misha2048 reviewed
Still smells like shit, 90/60/90 like

2024-02-20 07:59 UTC, Misha2048 approved these changes

2024-02-20 08:08 UTC, merged