feature/scrum-207 don't show private stillages
Misha2048/CatharsisX-back pull request #98
Opened 2024-02-19 18:20 UTC by PavloDolia

2024-02-19 19:44 UTC, Misha2048 requested changes

2024-02-19 19:44 UTC, Misha2048 commented on src/modules/stillages/stillages.service.ts
> +        if (!stillage.private || stillage.userId === userId) {
Это условие должно быть в запросе, а не в сервисе

2024-02-19 19:44 UTC, Misha2048 commented on src/modules/stillages/stillages.service.ts
> +      if (!stillage.private || stillage.userId === userId) {
Аналогично, если эту логику поместить запрос, то время ответа кратно сократиться

2024-02-19 20:53 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +        if (!stillage.private || stillage.userId === userId) {
переробив

2024-02-19 20:53 UTC, PavloDolia commented on src/modules/stillages/stillages.service.ts
> +      if (!stillage.private || stillage.userId === userId) {
переробив

2024-02-20 08:02 UTC, Misha2048 approved these changes

2024-02-20 09:29 UTC, Spinkll approved these changes

2024-02-20 09:29 UTC, Daniel04203 approved these changes

2024-02-20 09:30 UTC, merged